<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
	DB::table('countries')->delete();
	$now = date("Y-m-d H:i:s");
	$countries = array(
		array("id" => 1, "name" => "Afghanistan","code" => "AF","phonecode" => 93, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 2, "name" => "Aland Islands","code" => "AX","phonecode" => 35818, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 3, "name" => "Albania","code" => "AL","phonecode" => 355, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 4, "name" => "Algeria","code" => "DZ","phonecode" => 213, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 5, "name" => "American Samoa","code" => "AS","phonecode" => 1684, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 6, "name" => "Andorra","code" => "AD","phonecode" => 376, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 7, "name" => "Angola","code" => "AO","phonecode" => 244, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 8, "name" => "Anguilla","code" => "AI","phonecode" => 1264, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 9, "name" => "Antarctica","code" => "AQ","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 10, "name" => "Antigua And Barbuda","code" => "AG","phonecode" => 1268, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 11, "name" => "Argentina","code" => "AR","phonecode" => 54, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 12, "name" => "Armenia","code" => "AM","phonecode" => 374, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 13, "name" => "Aruba","code" => "AW","phonecode" => 297, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 14, "name" => "Australia","code" => "AU","phonecode" => 61, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 15, "name" => "Austria","code" => "AT","phonecode" => 43, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 16, "name" => "Azerbaijan","code" => "AZ","phonecode" => 994, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 17, "name" => "Bahamas The","code" => "BS","phonecode" => 1242, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 18, "name" => "Bahrain","code" => "BH","phonecode" => 973, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 19, "name" => "Bangladesh","code" => "BD","phonecode" => 880, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 20, "name" => "Barbados","code" => "BB","phonecode" => 1246, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 21, "name" => "Belarus","code" => "BY","phonecode" => 375, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 22, "name" => "Belgium","code" => "BE","phonecode" => 32, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 23, "name" => "Belize","code" => "BZ","phonecode" => 501, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 24, "name" => "Benin","code" => "BJ","phonecode" => 229, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 25, "name" => "Bermuda","code" => "BM","phonecode" => 1441, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 26, "name" => "Bhutan","code" => "BT","phonecode" => 975, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 27, "name" => "Bolivia","code" => "BO","phonecode" => 591, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 28, "name" => "Bosnia and Herzegovina","code" => "BA","phonecode" => 387, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 29, "name" => "Botswana","code" => "BW","phonecode" => 267, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 30, "name" => "Bouvet Island","code" => "BV","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 31, "name" => "Brazil","code" => "BR","phonecode" => 55, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 32, "name" => "British Indian Ocean Territory","code" => "IO","phonecode" => 246, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 33, "name" => "Brunei","code" => "BN","phonecode" => 673, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 34, "name" => "Bulgaria","code" => "BG","phonecode" => 359, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 35, "name" => "Burkina Faso","code" => "BF","phonecode" => 226, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 36, "name" => "Burundi","code" => "BI","phonecode" => 257, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 37, "name" => "Cambodia","code" => "KH","phonecode" => 855, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 38, "name" => "Cameroon","code" => "CM","phonecode" => 237, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 39, "name" => "Canada","code" => "CA","phonecode" => 1, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 40, "name" => "Cape Verde","code" => "CV","phonecode" => 238, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 41, "name" => "Cayman Islands","code" => "KY","phonecode" => 1345, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 42, "name" => "Central African Republic","code" => "CF","phonecode" => 236, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 43, "name" => "Chad","code" => "TD","phonecode" => 235, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 44, "name" => "Chile","code" => "CL","phonecode" => 56, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 45, "name" => "China","code" => "CN","phonecode" => 86, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 46, "name" => "Christmas Island","code" => "CX","phonecode" => 61, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 47, "name" => "Cocos (Keeling) Islands","code" => "CC","phonecode" => 61, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 48, "name" => "Colombia","code" => "CO","phonecode" => 57, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 49, "name" => "Comoros","code" => "KM","phonecode" => 269, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 50, "name" => "Congo","code" => "CG","phonecode" => 242, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 51, "name" => "Congo The Democratic Republic Of The","code" => "CD","phonecode" => 243, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 52, "name" => "Cook Islands","code" => "CK","phonecode" => 682, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 53, "name" => "Costa Rica","code" => "CR","phonecode" => 506, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 54, "name" => "Cote D'Ivoire (Ivory Coast)","code" => "CI","phonecode" => 225, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 55, "name" => "Croatia (Hrvatska)","code" => "HR","phonecode" => 385, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 56, "name" => "Cuba","code" => "CU","phonecode" => 53, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 57, "name" => "Cyprus","code" => "CY","phonecode" => 357, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 58, "name" => "Czech Republic","code" => "CZ","phonecode" => 420, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 59, "name" => "Denmark","code" => "DK","phonecode" => 45, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 60, "name" => "Djibouti","code" => "DJ","phonecode" => 253, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 61, "name" => "Dominica","code" => "DM","phonecode" => 1767, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 62, "name" => "Dominican Republic","code" => "DO","phonecode" => 1809, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 63, "name" => "East Timor","code" => "TL","phonecode" => 670, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 64, "name" => "Ecuador","code" => "EC","phonecode" => 593, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 65, "name" => "Egypt","code" => "EG","phonecode" => 20, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 66, "name" => "El Salvador","code" => "SV","phonecode" => 503, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 67, "name" => "Equatorial Guinea","code" => "GQ","phonecode" => 240, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 68, "name" => "Eritrea","code" => "ER","phonecode" => 291, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 69, "name" => "Estonia","code" => "EE","phonecode" => 372, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 70, "name" => "Ethiopia","code" => "ET","phonecode" => 251, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 71, "name" => "Falkland Islands","code" => "FK","phonecode" => 500, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 72, "name" => "Faroe Islands","code" => "FO","phonecode" => 298, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 73, "name" => "Fiji Islands","code" => "FJ","phonecode" => 679, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 74, "name" => "Finland","code" => "FI","phonecode" => 358, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 75, "name" => "France","code" => "FR","phonecode" => 33, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 76, "name" => "French Guiana","code" => "GF","phonecode" => 594, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 77, "name" => "French Polynesia","code" => "PF","phonecode" => 689, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 78, "name" => "French Southern Territories","code" => "TF","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 79, "name" => "Gabon","code" => "GA","phonecode" => 241, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 80, "name" => "Gambia The","code" => "GM","phonecode" => 220, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 81, "name" => "Georgia","code" => "GE","phonecode" => 995, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 82, "name" => "Germany","code" => "DE","phonecode" => 49, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 83, "name" => "Ghana","code" => "GH","phonecode" => 233, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 84, "name" => "Gibraltar","code" => "GI","phonecode" => 350, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 85, "name" => "Greece","code" => "GR","phonecode" => 30, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 86, "name" => "Greenland","code" => "GL","phonecode" => 299, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 87, "name" => "Grenada","code" => "GD","phonecode" => 1473, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 88, "name" => "Guadeloupe","code" => "GP","phonecode" => 590, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 89, "name" => "Guam","code" => "GU","phonecode" => 1671, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 90, "name" => "Guatemala","code" => "GT","phonecode" => 502, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 91, "name" => "Guernsey and Alderney","code" => "GG","phonecode" => 441481, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 92, "name" => "Guinea","code" => "GN","phonecode" => 224, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 93, "name" => "Guinea-Bissau","code" => "GW","phonecode" => 245, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 94, "name" => "Guyana","code" => "GY","phonecode" => 592, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 95, "name" => "Haiti","code" => "HT","phonecode" => 509, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 96, "name" => "Heard and McDonald Islands","code" => "HM","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 97, "name" => "Honduras","code" => "HN","phonecode" => 504, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 98, "name" => "Hong Kong S.A.R.","code" => "HK","phonecode" => 852, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 99, "name" => "Hungary","code" => "HU","phonecode" => 36, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 100, "name" => "Iceland","code" => "IS","phonecode" => 354, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 101, "name" => "India","code" => "IN","phonecode" => 91, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 102, "name" => "Indonesia","code" => "ID","phonecode" => 62, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 103, "name" => "Iran","code" => "IR","phonecode" => 98, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 104, "name" => "Iraq","code" => "IQ","phonecode" => 964, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 105, "name" => "Ireland","code" => "IE","phonecode" => 353, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 106, "name" => "Israel","code" => "IL","phonecode" => 972, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 107, "name" => "Italy","code" => "IT","phonecode" => 39, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 108, "name" => "Jamaica","code" => "JM","phonecode" => 1876, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 109, "name" => "Japan","code" => "JP","phonecode" => 81, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 110, "name" => "Jersey","code" => "JE","phonecode" => 441534, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 111, "name" => "Jordan","code" => "JO","phonecode" => 962, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 112, "name" => "Kazakhstan","code" => "KZ","phonecode" => 7, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 113, "name" => "Kenya","code" => "KE","phonecode" => 254, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 114, "name" => "Kiribati","code" => "KI","phonecode" => 686, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 115, "name" => "Korea North","code" => "KP","phonecode" => 850, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 116, "name" => "Korea South","code" => "KR","phonecode" => 82, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 117, "name" => "Kuwait","code" => "KW","phonecode" => 965, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 118, "name" => "Kyrgyzstan","code" => "KG","phonecode" => 996, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 119, "name" => "Laos","code" => "LA","phonecode" => 856, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 120, "name" => "Latvia","code" => "LV","phonecode" => 371, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 121, "name" => "Lebanon","code" => "LB","phonecode" => 961, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 122, "name" => "Lesotho","code" => "LS","phonecode" => 266, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 123, "name" => "Liberia","code" => "LR","phonecode" => 231, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 124, "name" => "Libya","code" => "LY","phonecode" => 218, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 125, "name" => "Liechtenstein","code" => "LI","phonecode" => 423, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 126, "name" => "Lithuania","code" => "LT","phonecode" => 370, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 127, "name" => "Luxembourg","code" => "LU","phonecode" => 352, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 128, "name" => "Macau S.A.R.","code" => "MO","phonecode" => 853, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 129, "name" => "Macedonia","code" => "MK","phonecode" => 389, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 130, "name" => "Madagascar","code" => "MG","phonecode" => 261, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 131, "name" => "Malawi","code" => "MW","phonecode" => 265, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 132, "name" => "Malaysia","code" => "MY","phonecode" => 60, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 133, "name" => "Maldives","code" => "MV","phonecode" => 960, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 134, "name" => "Mali","code" => "ML","phonecode" => 223, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 135, "name" => "Malta","code" => "MT","phonecode" => 356, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 136, "name" => "Man (Isle of)","code" => "IM","phonecode" => 441624, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 137, "name" => "Marshall Islands","code" => "MH","phonecode" => 692, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 138, "name" => "Martinique","code" => "MQ","phonecode" => 596, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 139, "name" => "Mauritania","code" => "MR","phonecode" => 222, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 140, "name" => "Mauritius","code" => "MU","phonecode" => 230, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 141, "name" => "Mayotte","code" => "YT","phonecode" => 262, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 142, "name" => "Mexico","code" => "MX","phonecode" => 52, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 143, "name" => "Micronesia","code" => "FM","phonecode" => 691, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 144, "name" => "Moldova","code" => "MD","phonecode" => 373, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 145, "name" => "Monaco","code" => "MC","phonecode" => 377, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 146, "name" => "Mongolia","code" => "MN","phonecode" => 976, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 147, "name" => "Montenegro","code" => "ME","phonecode" => 382, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 148, "name" => "Montserrat","code" => "MS","phonecode" => 1664, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 149, "name" => "Morocco","code" => "MA","phonecode" => 212, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 150, "name" => "Mozambique","code" => "MZ","phonecode" => 258, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 151, "name" => "Myanmar","code" => "MM","phonecode" => 95, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 152, "name" => "Namibia","code" => "NA","phonecode" => 264, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 153, "name" => "Nauru","code" => "NR","phonecode" => 674, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 154, "name" => "Nepal","code" => "NP","phonecode" => 977, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 155, "name" => "Netherlands Antilles","code" => "AN","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 156, "name" => "Netherlands The","code" => "NL","phonecode" => 31, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 157, "name" => "New Caledonia","code" => "NC","phonecode" => 687, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 158, "name" => "New Zealand","code" => "NZ","phonecode" => 64, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 159, "name" => "Nicaragua","code" => "NI","phonecode" => 505, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 160, "name" => "Niger","code" => "NE","phonecode" => 227, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 161, "name" => "Nigeria","code" => "NG","phonecode" => 234, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 162, "name" => "Niue","code" => "NU","phonecode" => 683, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 163, "name" => "Norfolk Island","code" => "NF","phonecode" => 672, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 164, "name" => "Northern Mariana Islands","code" => "MP","phonecode" => 1670, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 165, "name" => "Norway","code" => "NO","phonecode" => 47, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 166, "name" => "Oman","code" => "OM","phonecode" => 968, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 167, "name" => "Pakistan","code" => "PK","phonecode" => 92, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 168, "name" => "Palau","code" => "PW","phonecode" => 680, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 169, "name" => "Palestinian Territory Occupied","code" => "PS","phonecode" => 970, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 170, "name" => "Panama","code" => "PA","phonecode" => 507, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 171, "name" => "Papua new Guinea","code" => "PG","phonecode" => 675, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 172, "name" => "Paraguay","code" => "PY","phonecode" => 595, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 173, "name" => "Peru","code" => "PE","phonecode" => 51, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 174, "name" => "Philippines","code" => "PH","phonecode" => 63, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 175, "name" => "Pitcairn Island","code" => "PN","phonecode" => 870, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 176, "name" => "Poland","code" => "PL","phonecode" => 48, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 177, "name" => "Portugal","code" => "PT","phonecode" => 351, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 178, "name" => "Puerto Rico","code" => "PR","phonecode" => 1787, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 179, "name" => "Qatar","code" => "QA","phonecode" => 974, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 180, "name" => "Reunion","code" => "RE","phonecode" => 262, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 181, "name" => "Romania","code" => "RO","phonecode" => 40, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 182, "name" => "Russia","code" => "RU","phonecode" => 7, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 183, "name" => "Rwanda","code" => "RW","phonecode" => 250, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 184, "name" => "Saint Helena","code" => "SH","phonecode" => 290, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 185, "name" => "Saint Kitts And Nevis","code" => "KN","phonecode" => 1869, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 186, "name" => "Saint Lucia","code" => "LC","phonecode" => 1758, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 187, "name" => "Saint Pierre and Miquelon","code" => "PM","phonecode" => 508, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 188, "name" => "Saint Vincent And The Grenadines","code" => "VC","phonecode" => 1784, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 189, "name" => "Saint-Barthelemy","code" => "BL","phonecode" => 590, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 190, "name" => "Saint-Martin (French part)","code" => "MF","phonecode" => 590, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 191, "name" => "Samoa","code" => "WS","phonecode" => 685, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 192, "name" => "San Marino","code" => "SM","phonecode" => 378, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 193, "name" => "Sao Tome and Principe","code" => "ST","phonecode" => 239, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 194, "name" => "Saudi Arabia","code" => "SA","phonecode" => 966, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 195, "name" => "Senegal","code" => "SN","phonecode" => 221, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 196, "name" => "Serbia","code" => "RS","phonecode" => 381, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 197, "name" => "Seychelles","code" => "SC","phonecode" => 248, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 198, "name" => "Sierra Leone","code" => "SL","phonecode" => 232, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 199, "name" => "Singapore","code" => "SG","phonecode" => 65, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 200, "name" => "Slovakia","code" => "SK","phonecode" => 421, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 201, "name" => "Slovenia","code" => "SI","phonecode" => 386, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 202, "name" => "Solomon Islands","code" => "SB","phonecode" => 677, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 203, "name" => "Somalia","code" => "SO","phonecode" => 252, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 204, "name" => "South Africa","code" => "ZA","phonecode" => 27, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 205, "name" => "South Georgia","code" => "GS","phonecode" => 0, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 206, "name" => "South Sudan","code" => "SS","phonecode" => 211, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 207, "name" => "Spain","code" => "ES","phonecode" => 34, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 208, "name" => "Sri Lanka","code" => "LK","phonecode" => 94, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 209, "name" => "Sudan","code" => "SD","phonecode" => 249, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 210, "name" => "Suriname","code" => "SR","phonecode" => 597, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 211, "name" => "Svalbard And Jan Mayen Islands","code" => "SJ","phonecode" => 47, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 212, "name" => "Swaziland","code" => "SZ","phonecode" => 268, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 213, "name" => "Sweden","code" => "SE","phonecode" => 46, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 214, "name" => "Switzerland","code" => "CH","phonecode" => 41, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 215, "name" => "Syria","code" => "SY","phonecode" => 963, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 216, "name" => "Taiwan","code" => "TW","phonecode" => 886, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 217, "name" => "Tajikistan","code" => "TJ","phonecode" => 992, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 218, "name" => "Tanzania","code" => "TZ","phonecode" => 255, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 219, "name" => "Thailand","code" => "TH","phonecode" => 66, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 220, "name" => "Togo","code" => "TG","phonecode" => 228, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 221, "name" => "Tokelau","code" => "TK","phonecode" => 690, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 222, "name" => "Tonga","code" => "TO","phonecode" => 676, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 223, "name" => "Trinidad And Tobago","code" => "TT","phonecode" => 1868, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 224, "name" => "Tunisia","code" => "TN","phonecode" => 216, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 225, "name" => "Turkey","code" => "TR","phonecode" => 90, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 226, "name" => "Turkmenistan","code" => "TM","phonecode" => 993, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 227, "name" => "Turks And Caicos Islands","code" => "TC","phonecode" => 1649, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 228, "name" => "Tuvalu","code" => "TV","phonecode" => 688, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 229, "name" => "Uganda","code" => "UG","phonecode" => 256, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 230, "name" => "Ukraine","code" => "UA","phonecode" => 380, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 231, "name" => "United Arab Emirates","code" => "AE","phonecode" => 971, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 232, "name" => "United Kingdom","code" => "GB","phonecode" => 44, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 233, "name" => "United States","code" => "US","phonecode" => 1, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 234, "name" => "United States Minor Outlying Islands","code" => "UM","phonecode" => 1, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 235, "name" => "Uruguay","code" => "UY","phonecode" => 598, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 236, "name" => "Uzbekistan","code" => "UZ","phonecode" => 998, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 237, "name" => "Vanuatu","code" => "VU","phonecode" => 678, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 238, "name" => "Vatican City State (Holy See)","code" => "VA","phonecode" => 379, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 239, "name" => "Venezuela","code" => "VE","phonecode" => 58, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 240, "name" => "Vietnam","code" => "VN","phonecode" => 84, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 241, "name" => "Virgin Islands (British)","code" => "VG","phonecode" => 1284, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 242, "name" => "Virgin Islands (US)","code" => "VI","phonecode" => 1340, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 243, "name" => "Wallis And Futuna Islands","code" => "WF","phonecode" => 681, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 244, "name" => "Western Sahara","code" => "EH","phonecode" => 212, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 245, "name" => "Yemen","code" => "YE","phonecode" => 967, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 246, "name" => "Zambia","code" => "ZM","phonecode" => 260, 'created_at'=>$now,'updated_at'=>$now),
		array("id" => 247, "name" => "Zimbabwe","code" => "ZW","phonecode" => 263, 'created_at'=>$now,'updated_at'=>$now),
		);
		DB::table('countries')->insert($countries);
	}
}
